### PR TITLE
[translation/Japanese] Fixed some translations and added README-ja.md

### PR DESCRIPTION
**Pull request by cmplstofB**
I fixed some Japanese translations, and added README-ja.md, Japanese translation of README.md.
Would you please merge them?
(I'm sorry to bother you with frequent pull requests...)

### CODE REVIEW

**Comment by HajoRijgersberg** [comment]
Thanks so much! I'll look at it soon, intend do that at the beginning of this week.
No, you don't have to say sorry; I really appreciate your effort! :)

**Comment by HajoRijgersberg** [comment]
It'll be a little later due to busy times! 2nd half of this week! :)

**Comment by cmplstofB** [comment]
*(I found a new translation error and corrected it)*

**Comment by HajoRijgersberg** [comment]
I'll have a look at it too; thanx!

**Comment by HajoRijgersberg** [comment]
I have merged your changes! :)
Could you please have a look whether I have done everything correctly? Still getting used to GitHub...
Thanks so much!

**Pull request merged**
