### PR TITLE
reclassify owl:Thing -> owl:NamedIndividual

### PR DESCRIPTION
**Pull request by jmkeil**
This PR reclassifies some resources from owl:Thing to owl:NamedIndividual.

This has no effect from the domain perspective, but fixes the following violations of the OWL 2 RL profile (see #79):

```
Use of non-superclass expression in position that requires a superclass expression: owl:Thing [ClassAssertion(owl:Thing <http://www.ontology-of-units-of-measure.org/resource/om-2/_9192631770PeriodsOfTheRadiationCorrespondingToTheTransitionBetweenTheTwoHyperfineLevelsOfTheGroundStateOfTheCesium133Atom>) in OntologyID(OntologyIRI(<http://www.ontology-of-units-of-measure.org/resource/om-2>) VersionIRI(<null>))]
Use of non-superclass expression in position that requires a superclass expression: owl:Thing [ClassAssertion(owl:Thing <http://www.ontology-of-units-of-measure.org/resource/om-2/internationalPrototypeOfTheKilogram>) in OntologyID(OntologyIRI(<http://www.ontology-of-units-of-measure.org/resource/om-2>) VersionIRI(<null>))]
Use of non-superclass expression in position that requires a superclass expression: owl:Thing [ClassAssertion(owl:Thing <http://www.ontology-of-units-of-measure.org/resource/om-2/oneBinaryDigit>) in OntologyID(OntologyIRI(<http://www.ontology-of-units-of-measure.org/resource/om-2>) VersionIRI(<null>))]
Use of non-superclass expression in position that requires a superclass expression: owl:Thing [ClassAssertion(owl:Thing <http://www.ontology-of-units-of-measure.org/resource/om-2/pathTravelledByLightInVacuumDuringATimeIntervalOf1299792458OfASecond>) in OntologyID(OntologyIRI(<http://www.ontology-of-units-of-measure.org/resource/om-2>) VersionIRI(<null>))]
Use of non-superclass expression in position that requires a superclass expression: owl:Thing [ClassAssertion(owl:Thing <http://www.ontology-of-units-of-measure.org/resource/om-2/systemThatContainsAsManyElementaryEntitiesAsThereAreAtomsIn0.012KilogramOfCarbon12>) in OntologyID(OntologyIRI(<http://www.ontology-of-units-of-measure.org/resource/om-2>) VersionIRI(<null>))]
Use of non-superclass expression in position that requires a superclass expression: owl:Thing [ClassAssertion(owl:Thing <http://www.ontology-of-units-of-measure.org/resource/om-2/triplePointOfWater>) in OntologyID(OntologyIRI(<http://www.ontology-of-units-of-measure.org/resource/om-2>) VersionIRI(<null>))]
```

### CODE REVIEW

**Comment by jmkeil** [comment]
@HajoRijgersberg: Do you have any concerns regarding this PR?

**Comment by HajoRijgersberg** [comment]
My apologies, Jan Martin, last month has been crazy with many, many projects, deadlines, etc. And I became a father again from a lovely daughter <3, Aurora; she and her mother are doing very fine, but Aurora came two weeks earlier than originally expected, as a result of which I got in trouble with exchanging tasks including leading tasks in the aforementioned projects. I come back to your messages and actions as soon as possible, I expect within a range of a few days till a few weeks. Hope that is Ok with you! Thank you so much for all your actions so far, and understanding in advance! ;)

**Comment by jmkeil** [comment]
Congratulations and all the best to all of you. Be assured you have my full understanding.

**Comment by HajoRijgersberg** [comment]
Thanx Jan Martin, I really appreciate that!

**Comment by HajoRijgersberg** [comment]
Hey, I would like to merge this PR, but as an experiment (for me anyway) I would like to change the version number and date in the file. Before I would do that, I would like to reflect this with you, also so that you would not be surprised by it. Looking forward to your response. Many thanx again in advance!

**Comment by jmkeil** [comment]
Sure. Just try it.

**Review by HajoRijgersberg — APPROVED** [review]

**Comment by HajoRijgersberg** [comment]
It worked, thanx for all your effort, help and patience, and I'll dive in your other posts soon!

**Comment by jmkeil** [comment]
Thank you for merging.

**Pull request merged**
