### PR TITLE
Automated deviation check to other ontologies using ABECTO

### PR DESCRIPTION
**Pull request by jmkeil**
Hi. This adds a configuration to automatically compare your ontology with other unit ontologies using [ABECTO](https://github.com/fusion-jena/abecto) after each commit and to return a table of found deviations. Maybe you are interested to use this.

### CODE REVIEW

**Comment by jmkeil** [comment]
On https://github.com/jmkeil/OM/actions/runs/2698512808 you can find a preview how the results will look like. The job is marked as failed, because deviations have been found. Deviations can be handled by
* fixing the own ontology,
* fixing the other ontology, or
* annotating the other ontologies value wrong in the comparison configuration: e.g. https://github.com/HajoRijgersberg/OM/pull/69/commits/dfe70dbbe8d443e320758355452635cae6fb8713#diff-e0d32ca090299210a370686a02bb14187a858eca375264f7e9a3c8316721eda5R825, an appropriate snippet is provided in the last column of the result table.

Alternatively, the parameter `--failOnDeviation` in https://github.com/HajoRijgersberg/OM/pull/69/commits/fc6f2a79a34ceb60c56d71972d831923fcf4912b#diff-311f6477bc95af7ccedbe3225a241452ddb76b61cea146f6103c84a5059d6fb8R12 can be removed. Then the job will only fail, if the comparison could not be executed for any reason.

**Comment by HajoRijgersberg** [comment]
Hi Jan Martin,

Thanx so much for your effort and sorry for my late reply!
I have to schedule some time to study this. I intend to come back to this on short terms. I'll keep you updated!
Perhaps I need some help from your side for a full understanding.

Cheers, Hajo

**Comment by jmkeil** [comment]
I just updated the comparison configuration, revealing further deviations.

**Comment by HajoRijgersberg** [comment]
Thanx again, Jan Martin! I'm still looking for time to study the changes, it's on my to-do list. I hope to update you soon!
Cheers, Hajo

**Pull request merged**
